#!/usr/bin/env sh

set -euo pipefail

PROJECT=$PWD
REPO=$(mktemp -d)

echo $REPO

git clone --depth=1 $1 $REPO
cd $REPO

echo "cp \"$PROJECT/$2\" \"$2\""
cp "$PROJECT/$2" "$2"

echo "git add $2"
git add $2

echo "git commit -m \"docs: update changelog\""
git commit -m "docs: update changelog"

echo "git push origin $3"
git push origin $3

cd "$PROJECT"
rm -rf "$REPO"
